import autoUsado from './autoUsado.jpg';

const autosEnVenta = [
  {
    id: '1',
    imagenAuto: autoUsado,
    precio: 2835000,
    patente: 'ABC123',
    sucursal: 'Sucursal A',
    anio: 2020,
    marca: 'Toyota',
    modelo: 'Corolla',
    kilometraje: 5000,
    combustible: 'Nafta',
    importado: 'no',
    reserva: 'si',
  },
  {
    id: '2',
    imagenAuto: autoUsado,
    precio: 10560000,
    patente: 'DEF456',
    sucursal: 'Sucursal B',
    anio: 2019,
    marca: 'Honda',
    modelo: 'Civic',
    kilometraje: 8000,
    combustible: 'Nafta',
    importado: 'no',
    reserva: 'no',
  },
  {
    id: '3',
    imagenAuto: autoUsado,
    precio: 13009400,
    patente: 'GHI789',
    sucursal: 'Sucursal C',
    anio: 2021,
    marca: 'Ford',
    modelo: 'Mustang',
    kilometraje: 3000,
    combustible: 'Nafta',
    importado: 'si',
    reserva: 'si',
  },
  {
    id: '4',
    imagenAuto: autoUsado,
    precio: 5000000,
    patente: 'JKL012',
    sucursal: 'Sucursal A',
    anio: 2022,
    marca: 'Chevrolet',
    modelo: 'Camaro',
    kilometraje: 2000,
    combustible: 'Nafta',
    importado: 'no',
    reserva: 'no',
  },
  {
    id: '5',
    imagenAuto: autoUsado,
    precio: 2000000,
    patente: 'MNO345',
    sucursal: 'Sucursal B',
    anio: 2020,
    marca: 'Volkswagen',
    modelo: 'Golf',
    kilometraje: 7000,
    combustible: 'Nafta',
    importado: 'no',
    reserva: 'si',
  },
  {
    id: '6',
    imagenAuto: autoUsado,
    precio: 10375000,
    patente: 'PQR678',
    sucursal: 'Sucursal C',
    anio: 2019,
    marca: 'Toyota',
    modelo: 'Rav4',
    kilometraje: 10000,
    combustible: 'Híbrido',
    importado: 'no',
    reserva: 'no',
  },
  {
    id: '7',
    imagenAuto: autoUsado,
    precio: 8560000,
    patente: 'STU901',
    sucursal: 'Sucursal A',
    anio: 2021,
    marca: 'Mazda',
    modelo: 'CX-5',
    kilometraje: 4000,
    combustible: 'Nafta',
    importado: 'si',
    reserva: 'si',
  },
  {
    id: '8',
    imagenAuto: autoUsado,
    precio: 14790000,
    patente: 'VWX234',
    sucursal: 'Sucursal B',
    anio: 2022,
    marca: 'Nissan',
    modelo: 'Sentra',
    kilometraje: 3000,
    combustible: 'Nafta',
    importado: 'no',
    reserva: 'no',
  },
  {
    id: '9',
    precio: 13456700,
    imagenAuto: autoUsado,
    patente: 'YZA567',
    sucursal: 'Sucursal C',
    anio: 2020,
    marca: 'Honda',
    modelo: 'Accord',
    kilometraje: 6000,
    combustible: 'Nafta',
    importado: 'no',
    reserva: 'si',
  },
  {
    id: '10',
    imagenAuto: autoUsado,
    precio: 3897456,
    patente: 'BCD890',
    sucursal: 'Sucursal A',
    anio: 2021,
    marca: 'Ford',
    modelo: 'Explorer',
    kilometraje: 8000,
    combustible: 'Nafta',
    importado: 'si',
    reserva: 'no',
  },
  {
    id: 21,
    imagenAuto: autoUsado,
    precio: 9456000,
    patente: 'XYZ987',
    sucursal: 'Sucursal B',
    marca: 'Volkswagen',
    anio: 2021,
    modelo: 'Tiguan',
    kilometraje: 5000,
    combustible: 'Diésel',
    importado: 'no',
    reserva: 'si',
  },
];

export default autosEnVenta;
