const Roles = Object.freeze({
  CLIENTE: 'CLIENTE',
  ADMINISTRADOR: 'ADMINISTRADOR',
  TECNICO: 'TECNICO',
  VENDEDOR: 'VENDEDOR',
  SUPERVISOR_TECNICO: 'SUPERVISOR_TECNICO',
  SUPERVISOR_VENTAS: 'SUPERVISOR_VENTAS',
  GERENTE_SUCURSAL: 'GERENTE_SUCURSAL',
  GERENTE_GENERAL: 'GERENTE_GENERAL',
  IT: 'IT',
});

export default Roles;
