export const products=[
  {
    "id": "1",
    "patente": "ABC123",
    "sucursal": "Sucursal A",
    "anio": 2020,
    "marca": "Toyota",
    "modelo": "Corolla",
    "kilometraje": 5000,
    "combustible": "Nafta",
    "importado": "no",
    "reserva": "si"
  },
  {
    "id": "2",
    "patente": "DEF456",
    "sucursal": "Sucursal B",
    "anio": 2019,
    "marca": "Honda",
    "modelo": "Civic",
    "kilometraje": 8000,
    "combustible": "Nafta",
    "importado": "no",
    "reserva": "no"
  },
  {
    "id": "3",
    "patente": "GHI789",
    "sucursal": "Sucursal C",
    "anio": 2021,
    "marca": "Ford",
    "modelo": "Mustang",
    "kilometraje": 3000,
    "combustible": "Nafta",
    "importado": "si",
    "reserva": "si"
  },
  {
    "id": "4",
    "patente": "JKL012",
    "sucursal": "Sucursal A",
    "anio": 2022,
    "marca": "Chevrolet",
    "modelo": "Camaro",
    "kilometraje": 2000,
    "combustible": "Nafta",
    "importado": "no",
    "reserva": "no"
  },
  {
    "id": "5",
    "patente": "MNO345",
    "sucursal": "Sucursal B",
    "anio": 2020,
    "marca": "Volkswagen",
    "modelo": "Golf",
    "kilometraje": 7000,
    "combustible": "Nafta",
    "importado": "no",
    "reserva": "si"
  },
  {
    "id": "6",
    "patente": "PQR678",
    "sucursal": "Sucursal C",
    "anio": 2019,
    "marca": "Toyota",
    "modelo": "Rav4",
    "kilometraje": 10000,
    "combustible": "Híbrido",
    "importado": "no",
    "reserva": "no"
  },
  {
    "id": "7",
    "patente": "STU901",
    "sucursal": "Sucursal A",
    "anio": 2021,
    "marca": "Mazda",
    "modelo": "CX-5",
    "kilometraje": 4000,
    "combustible": "Nafta",
    "importado": "si",
    "reserva": "si"
  },
  {
    "id": "8",
    "patente": "VWX234",
    "sucursal": "Sucursal B",
    "anio": 2022,
    "marca": "Nissan",
    "modelo": "Sentra",
    "kilometraje": 3000,
    "combustible": "Nafta",
    "importado": "no",
    "reserva": "no"
  },
  {
    "id": "9",
    "patente": "YZA567",
    "sucursal": "Sucursal C",
    "anio": 2020,
    "marca": "Honda",
    "modelo": "Accord",
    "kilometraje": 6000,
    "combustible": "Nafta",
    "importado": "no",
    "reserva": "si"
    },
    {
    "id": "10",
    "patente": "BCD890",
    "sucursal": "Sucursal A",
    "anio": 2021,
    "marca": "Ford",
    "modelo": "Explorer",
    "kilometraje": 8000,
    "combustible": "Nafta",
    "importado": "si",
    "reserva": "no"
    },
    {
      "id": 21,
      "patente": "XYZ987",
      "sucursal": "Sucursal B",
      "marca": "Volkswagen",
      "anio": 2021,
      "modelo": "Tiguan",
      "kilometraje": 5000,
      "combustible": "Diésel",
      "importado": "no",
      "reserva": "si"
    }
]